version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
